#ros2 run llm_action llm_action_node --ros-args --params-file src/turret_control/config/slack_llm.yaml
llama_node:
  ros__parameters:
    slack_input_topic: "/slack_in"
    slack_output_topic: "/slack_out"

slack_node:
  ros__parameters:
    slack_token: "slack_token"
    slack_channel: "C064YL34N8G"
    bot_member_id: "U07BA0R2UQG"
    slack_input_topic: "/slack_in"
    slack_output_topic: "/slack_out"

llm_action_node:
  ros__parameters:
    ollama_url: "http://ollama-ros-service:11434"
    ollama_model: "llama3.2-vision"

llm_intent_ident_node:
  ros__parameters:
    input_topic: "/slack_in"
    output_topic: "/slack_out"